[project]
name = "nexus-local"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "=3.12"
authors = [
    { name = "Outliers Tech", email = "outliers91@gmail.com" }
]
dependencies = [
    "flet==0.80.4",
    "watchdog",
    "requests",
    "python-dotenv",
    "pydantic",
    "pandas",
    "lancedb",
    "pypdf",
    "ddgs==9.10.0",
    "langchain-core>=0.3.15",
    "langchain>=0.3.15",
    "langchain-community>=0.3.15",
    "langchain-classic>=0.3.15",
    "langchain-ollama>=0.2.0",
    "langchain-text-splitters>=0.3.0",
    "langgraph"
]

[dependency-groups]
dev = [
    "flet-cli=0.80.4",
    "flet-desktop-light=0.80.4",
    "flet-web=0.80.4",
]

[tool.flet]
org = "com.outliers"
product = "nexus-local"
company = "Outliers"
copyright = "Copyright (C) 2023-2026 by Asutosh Nayak"

[tool.flet.app]
path = "src"
